os: linux
dist: trusty
language: java
jdk:
- openjdk8
if: |
  (branch IN (master, dev) AND commit_message !~ /^(bumped version to|release:) (\d+(\.\d+){2})(-.+)?$/) \
  OR tag =~ /^(\d+(\.\d+){2})([-+][\w\-\.+]+)?$/
git:
  depth: false
env:
  global:
    secure: ZVUMvOZrc+w0ztG4opwooQm6/Tshj18yZq/EfaX4r1UdZJa8bw0eubA01IPJmFDeRC9g3JQ0kVanPdm8SI7Qn9X3urSKXkNDxfkginMx8rsrO6j+ecVQd4QbgvMXGbam56XpmOBAj/xvWvJT0/DIEoBlEEYiBPG4Z/SDnnXymLtt2v+Jq36Ie/l7uiXNVgbqosuXG8AiYJEgOKPGhmB5u/xe8tzrIum78TIKy85Z0Y6shHSNNPF7xreaCt569Jh9o/VPoPSiA+wDq2Pp2ypDHJJ7BnIgdOvRzlLz2h10MwUI2W1qAV9E3fVztfRSh5313icJ2YkkdBFzoYKTqINqf1/lBWTj31Klq+Mt+iLZNZGyAT6QOB+ov/1j+snr2rjDoWAgUCxWPq30xqh+Wv+jCgAtvxTX4ntQd16uSDqPiM7eFC306D3wk2NjfVnLuc1JlmIGCYaRAVCkOJbZfy0aL9riIdSrun4ZrCFrbGzd14dva2LEX7K2oveTOSE0uPe93zcIJR5l3D0dIJ+EFVCRE3Hw7Dmx7wlL+g5meKZFebPOw9MCJYV+BerpwL1s8VwURbMJMEGfP9PPXFYI5aQ1+Ge2sWvi1hCii3nnHKb3wW7QuCIqsZCiSxAMJWwXyzDonPfKSnraBFqGp4bXK4BZyoKZetZzf1weIwL0bhEJX48=
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
  - "$HOME/.gradle/caches/modules-2/"
  - "$HOME/.gradle/wrapper/dists/"
before_install:
- openssl aes-256-cbc -K $encrypted_70811ee8b6a1_key -iv $encrypted_70811ee8b6a1_iv
  -in .travis/secret.gpg.enc -out .travis/secret.gpg -d
- openssl aes-256-cbc -K $encrypted_2afbb999f001_key -iv $encrypted_2afbb999f001_iv
  -in gradle.properties.enc -out gradle.properties -d
- git config --global user.name "Travis CI"
- git config --global user.email "travis.ci@yi.team"
- chmod +x ./gradlew .travis/*.sh
- ls -lh
- git log --graph --full-history --all --color --date=short --pretty=format:"%Cred%x09%h
  %Creset%ad%Cgreen%d %Creset %s %C(bold)(%an)%Creset" || true
install: "/bin/true"
script:
- "./gradlew clean"
deploy:
- provider: script
  skip_cleanup: true
  cleanup: false
  script: ".travis/deploy-snapshot.sh"
  on:
    branch: master
- provider: script
  skip_cleanup: true
  cleanup: false
  script: ".travis/deploy-release.sh"
  on:
    tags: true
